services:
  # Frontend Next.js application
  projecthub-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_BASE_URL=http://projecthub-api:8080
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://projecthub-api:8080
      - BACKEND_API_URL=http://projecthub-api:8080
    depends_on:
      - projecthub-api
    networks:
      - projecthub-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # .NET Backend API
  projecthub-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/projecthub.db
    volumes:
      - ./data:/app/data
    networks:
      - projecthub-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/swagger/index.html"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Python LLM Service
  projecthub-ai:
    build:
      context: ./llm_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - BACKEND_API_URL=http://projecthub-api:8080
    depends_on:
      - projecthub-api
    networks:
      - projecthub-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  projecthub-network:
    driver: bridge 