name: ProjectHub CI/CD Pipeline

on:
  push:
    branches: [ tests ]
  pull_request:
    branches: [ tests ]

env:
  DOTNET_VERSION: '8.0.x'
  NODE_VERSION: '18'
  BACKEND_IMAGE: maksimsh20/projecthub-api:latest
  FRONTEND_IMAGE: maksimsh20/projecthub-frontend:latest
  AI_IMAGE: maksimsh20/projecthub-ai:latest

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Restore backend dependencies
        run: |
          cd ProjectHub/ProjectHub.API
          dotnet restore

      - name: Build backend
        run: |
          cd ProjectHub/ProjectHub.API
          dotnet build --configuration Release

      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore test dependencies
        run: |
          cd ProjectHub/NUnitTests
          dotnet restore

      - name: Build backend (for test)
        run: |
          cd ProjectHub/ProjectHub.API
          dotnet build --configuration Release

      - name: Build backend (for test)
        run: |
          cd ProjectHub/NUnitTests
          dotnet build --configuration Release

      - name: Run API and tests
        run: |
          cd ProjectHub/ProjectHub.API
          dotnet run --urls=http://localhost:7001 > api.log 2>&1 &
          API_PID=$!
          echo "Waiting for API to start..."
          for i in {1..10}; do
            if curl -s http://localhost:7001 > /dev/null; then
              echo "API is up!"
              break
            fi
            sleep 3
          done

          if ! curl -s http://localhost:7001 > /dev/null; then
            echo "API did not start in time"
            cat api.log
            kill $API_PID
            exit 1
          fi

          cd ../NUnitTests
          dotnet test --no-restore --logger "console;verbosity=detailed"
          kill $API_PID

  docker:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build backend image
        run: docker build -t ${{ env.BACKEND_IMAGE }} -f Dockerfile .

      - name: Build frontend image
        run: docker build -t ${{ env.FRONTEND_IMAGE }} ./frontend

      - name: Build AI image
        run: docker build -t ${{ env.AI_IMAGE }} ./llm_service

      - name: Push images
        run: |
          docker push ${{ env.BACKEND_IMAGE }}
          docker push ${{ env.FRONTEND_IMAGE }}
          docker push ${{ env.AI_IMAGE }}

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Backend API
        uses: azure/webapps-deploy@v2
        with:
          app-name: projecthub-api-app
          images: maksimsh20/projecthub-api

      - name: Deploy Frontend
        uses: azure/webapps-deploy@v2
        with:
          app-name: projecthub-frontend-app
          images: maksimsh20/projecthub-frontend

      - name: Deploy AI Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: projecthub-ai-app
          images: maksimsh20/projecthub-ai
